### ISSUE TITLE
Rename Dockerfile.lama to Dockerfile

### ISSUE THREAD

**Issue by qnbhd** [qnbhd/deployme#26]
Read title plz

CC: @pacifikus

**Comment by Lchris22** [comment]
Well, one of the tests failed after the change as there was a reference made to this file.
![image](https://user-images.githubusercontent.com/49443133/192001559-09da7a21-4edd-44d0-90c7-cb3a26e2010c.png)
Was the file intentionally named like this?

**Comment by pacifikus** [comment]
Thanks for the contribution @Lchris22 !
It looks like you need to make minor changes in [utils/utils.py](https://github.com/qnbhd/deployme/blob/main/deployme/utils/utils.py#L27) and rename `Dockerfile.lama` to `Dockerfile`

**Comment by Lchris22** [comment]
@pacifikus  I made the changes.  https://github.com/qnbhd/deployme/pull/41/commits/3ece4cefa29c8bd8404e4760367684e53d9a9fad
